スタート画面のモックアップを作成
ak03120/quiz-appl pull request #28
Opened 2023-05-26 02:08 UTC by ak03120

Close #2 
## Checklist for Developer
- [x] 最新のdevelopブランチをPullした。Pulled the latest develop branch.
  - できない理由 Reason not to do: 
- [x] Pull RequestをIssueに紐付けた。Connected with the issue.
- [x] 自分をAssignした。Assigned yourself.
- [x] レビュワーを指定した。Assigned reviewer.

## 📝 そのほかの関連するIssue / Related issues other than connected one

- #2 

## ⛏ 変更内容 / Details of Changes

- スタート画面のモックアップを作成しました。

## 📸 スクリーンショット / Screenshots

## レビューするポイント (Points for review):

- スタート画面が正しく表示されること。

2023-05-30 03:22 UTC, hikaru-nakamura-thedott commented
loginとstartはpagesというディレクトリを切ってそこにまとめましょうか！

2023-05-30 04:13 UTC, ak03120 commented
componentsフォルダからpagesフォルダにstartとloginコンポーネントを移動しました。

2023-05-30 07:42 UTC, hikaru-nakamura-thedott requested changes
ディレクトリ移動するに連れて各所のパスも変えてあげましょう。
また、些細な変更でも一応アプリケーションを起動して確認するようにしましょう。

2023-05-30 07:42 UTC, hikaru-nakamura-thedott commented on angular-app/src/app/app.module.ts
> +import { StartComponent } from './components/start/start.component';
ここのパス合ってますか？

2023-05-30 07:42 UTC, hikaru-nakamura-thedott commented on angular-app/src/app/app.module.ts
> +import { LoginComponent } from './components/login/login.component';
ここのパス合ってますか？

2023-05-30 15:07 UTC, ak03120 commented
パスを変更しました。
また、アプリケーションを起動して動作確認を行いました。

2023-05-31 02:40 UTC, hikaru-nakamura-thedott approved these changes

2023-05-31 02:40 UTC, merged