問題画面のモックアップを作成しました
ak03120/quiz-appl pull request #31
Opened 2023-06-07 05:23 UTC by ak03120

Close #4
## Checklist for Developer
- [x] 最新のdevelopブランチをPullした。Pulled the latest develop branch.
  - できない理由 Reason not to do: 
- [x] Pull RequestをIssueに紐付けた。Connected with the issue.
- [x] 自分をAssignした。Assigned yourself.
- [x] レビュワーを指定した。Assigned reviewer.

## 📝 そのほかの関連するIssue / Related issues other than connected one

- #4

## ⛏ 変更内容 / Details of Changes

- Questionコンポーネントを作成しました。
- 問題画面のモックアップを作成しました。

## 📸 スクリーンショット / Screenshots

![142209](https://github.com/ak03120/quiz-appl/assets/123559879/fd82f955-9661-4fa1-bb1e-45538cfcbd0e)

## レビューするポイント (Points for review):

- 問題画面が正しく表示される

2023-06-07 05:26 UTC, ak03120 commented on angular-app/src/app/pages/question/question.component.html
> +              <div class="radio-button-set">
文章と画像の選択肢はモックアップのため両方表示しています。

2023-06-08 10:06 UTC, hikaru-nakamura-thedott requested changes
HTML,CSSまわりの修正をお願いします。

2023-06-08 10:06 UTC, hikaru-nakamura-thedott commented on angular-app/src/app/pages/login/login.component.scss
> +h2, h3 {
すべてのh2, h3をセンター寄せするなら、styles.scssに書いてしまっても良い。
また、classを使用すると後で修正になっても楽。

```css
h2.centering-text, h3.centering-text{
  text-align: center;
}
```

2023-06-08 10:06 UTC, hikaru-nakamura-thedott commented on angular-app/src/app/pages/login/login.component.scss
> +div {
div に直書きは控えた方がいい。
classで対応しましょう。

2023-06-08 10:06 UTC, hikaru-nakamura-thedott commented on angular-app/src/app/pages/question/question.component.scss
> +mat-card-title, mat-radio-button {
angularマテリアルに直接スタイル書くのはやめましょう。

2023-06-08 10:06 UTC, hikaru-nakamura-thedott commented on angular-app/src/app/pages/start/start.component.html
> +        </button>
ボタンがセンターに来るようにしましょう

2023-06-08 10:06 UTC, hikaru-nakamura-thedott commented on angular-app/src/styles.scss
>  body { max-width: 800px; margin-left: auto; margin-right: auto; font-family: Roboto, "Helvetica Neue", sans-serif; }
bodyのレイアウトはできるだけいじらない！

2023-06-08 10:06 UTC, hikaru-nakamura-thedott commented on angular-app/src/app/pages/question/question.component.html
> +        <mat-card-title><b>回答</b></mat-card-title>
mat-card-titleにclassをつけてボジのレイアウトを調整しましょう！

2023-06-22 10:04 UTC, hikaru-nakamura-thedott requested changes

2023-06-22 10:04 UTC, hikaru-nakamura-thedott commented on angular-app/src/app/pages/login/login.component.html
> +        <div align="center" class="g_id_signin"
HTML要素の `align` プロパティは非推奨なので、 `text-align: center;` を使いましょう！
<img width="603" alt="スクリーンショット 2023-06-22 18 50 10" src="https://github.com/ak03120/quiz-appl/assets/86763776/c6eb5fa7-d459-4e77-a293-c304176fe8fa">

2023-06-22 10:04 UTC, hikaru-nakamura-thedott commented on angular-app/src/app/pages/question/question.component.html
> +          </mat-radio-group>
インデントズレ発見！

2023-06-22 10:04 UTC, hikaru-nakamura-thedott commented on angular-app/src/app/pages/question/question.component.scss
> +}
style.scssでも設定してるので重複しているのでは？

2023-06-22 10:04 UTC, hikaru-nakamura-thedott commented on angular-app/src/app/pages/question/question.component.html
> +    <mat-card-actions align="start">
`actions-left/right` で配置できているので、`align="start"` はいらないです〜

2023-06-22 10:16 UTC, hikaru-nakamura-thedott requested changes

2023-06-22 10:16 UTC, hikaru-nakamura-thedott commented on angular-app/src/styles.scss
> +  font-weight: bold!important; // importantがないとAngular Material?によって細字になる
```html
<span class="bold-text">問題</span>
```

2023-07-06 07:34 UTC, hikaru-nakamura-thedott approved these changes

2023-07-06 07:34 UTC, merged